#pragma once

enum class Engine_state{ IS_IN_MENU, IS_IN_LC, IS_IN_ANIMATION_MANAGEMENT, IS_IN_SCRIPT_EDITOR, IN_GAME, WON_KOLKO, WON_KRZYZYK, DRAW };
enum class Engine_updateState { NONE, RENDER_PREPARING, RENDER_READY };